
--
-- ESSE ARQUIVO AQUI NÃO SERVE DE NADA, É SÓ PRA MOSTRAR COMO É PARA CRIAR NO MYSQL WORKBENCH
--

create database db;
use db;

CREATE TABLE Usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ALTER TABLE Usuario
-- ADD COLUMN createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
-- ADD COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;



