
--
-- ESSE ARQUIVO AQUI É SÓ UMA BASE PARA VOCÊ CRIAR NO MYSQL WORKBENCH, NÃO PRECISA DESSE ARQUIVO .sql NO SEU PROJETO
-- aqui só precisa mudar esse 'db' para o nome do seu tema
--

create database db;
use db;

CREATE TABLE Usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ALTER TABLE Usuario
-- ADD COLUMN createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
-- ADD COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;



